sudo: false

language: node_js
node_js:
  - 8

env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9

install:
  - npm install
  - npm install -g firebase-tools
  - npm install -g coveralls

script:
  - npm run lint
  - npm run coverage

after_success:
  - cat ./coverage/lcov.info | coveralls
  - firebase deploy --token $FIREBASE_TOKEN