sudo: false

language: node_js
node_js:
  - 8

env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9

install:
  - npm install
  - npm install -g firebase-tools
  - npm install -g coveralls

script:
  - npm run lint
  - npm run coverage

after_success:
  - cat ./coverage/lcov.info | coveralls

deploy:
  provider: firebase
  token:
    secure: "BnqZsR5cLNv0mNqxqi4Zwf9ICVA85ol4hSLl1JHoLsqlERgxRDSmlTWQ6SmzX8E0I+kHMImqR6Amxh/8G94EW8EwdD/GQQSNw3fDqczqvM/l9uiviEqYEsTusPehDacUGq1EJbHy3Scg9DjBQWTCZp1SYqHaX35lZjppIDKlppPFROY4AMsMf9YRQy72cqeZl72rnZAQub8ZiRy0kCyr+ab9Omf71hwiJBGrEFHMpBoxzdYj5H19eqaI3qFx+2bmBl2VknRuBGuGEFXCfBNAgpeDIKGi1e3AH4s8NBToX2ogKVp+Ii78p9VW4HoZfxZ25mSTG1rENyO3/rJjRslQjh6cvXDG4cZuyDyh/u/POA7Bb1EeS/BtMQyyckc4Q8YTi26gku85Zw3k5W5vR/el2wh96tvmwu1w2PAYaA3L/asbzUdjj4EFB1fnXn7DiXydWwnK7zHgKY01u8Z7sUvsRfXxU8kepWTCeWvDyT/p9fvbVxosmkHvx2Q0LmfFrOqAetiAT6ogXnXuUkEHlHHqePtGWhfvvYayTBR9JlTCuxiQDz2RnbrmIvJU656MN7HHqiQosz1BcW1JkrGbiLmzCXFtewIVDM0DtUfbyXNaR3HU0i07y0MMxVFTofna5eo3WWRUhB7GgtiW4rmg3movxZoD5n2IQNtyil0lFrdZrys="
  skip_cleanup: true